 language: node_js
 node_js:
   - "12.18"
   - "14.7"
 script:
   - "echo 'running script'"
   - "npm run build && npm run test && npm run cover"
 after_script:
   - "echo 'running after_script'"
   - "cat ./coverage/lcov.info | coveralls"

